[package]

name = "x86_64"
version = "0.1.0"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
  "Eric Kidd <git@randomhacks.net>",
  "Philipp Oppermann <dev@phil-opp.com>",
  "Dan Schatzberg <schatzberg.dan@gmail.com>",
  "John Ericson <John_Ericson@Yahoo.com>",
  "Rex Lunae <rexlunae@gmail.com>"
]

description = "Library to program x86_64 hardware. Contains x86_64 specific data structure descriptions, data-tables, as well as convenience function to call assembly instructions. This is a fork of the `x86` crate, specialized for x86_64."

repository = "https://github.com/phil-opp/x86_64"
documentation = "https://docs.rs/x86_64"
readme = "README.md"
keywords = ["amd64", "x86", "x86_64", "no_std"]
license = "MIT"

[[test]]
name = "no_std_build"
harness = false

[dependencies]
bitflags = "0.7"
raw-cpuid = "2.*"
